# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/RHoumaidy/OneSignalSmart-ios.git'

target 'LVS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
   #use_frameworks!

  # Pods for LVS
	#pod 'OneSignalSmart', '~> 2.10.0'
  pod 'OneSignal', '>= 2.11.2', '< 3.0'
end

